"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";

type Step = "camera" | "analysing" | "analysis" | "nearby" | "builder" | "review" | "auth" | "submitting" | "success" | "track";
const address = "Road No. 36, Jubilee Hills, Hyderabad, Telangana 500033";
const issues = [
  ["Large pothole near Jubilee Hills Check Post", "Assigned", "80 m", "GRV-HYD-2026-18421", "14"],
  ["Water accumulation after road damage", "Under review", "160 m", "GRV-HYD-2026-18190", "7"],
];
const questions = [
  ["How long has this issue been present?", "Today|2–3 days|About a week|More than a week|Not sure"],
  ["How serious is the impact?", "Minor inconvenience|Difficult to use the road|Safety risk|Causing accidents|Blocking access"],
  ["Who is most affected?", "Pedestrians|Two-wheelers|Cars|Public transport|Elderly people|Children|Persons with disabilities|Nearby residents"],
  ["Is there any additional problem?", "Waterlogging|Poor street lighting|Open drain nearby|Traffic congestion|No warning barricade|None"],
  ["Have you noticed any immediate danger?", "Yes — accident risk|Yes — vehicle damage|Yes — flooding|No|Not sure"],
  ["Anything else you want to add?", "No, that’s all|It gets worse after rain|This is near a busy crossing|Add a voice note"],
];
const initialTitle = "Large pothole and water accumulation creating a road-safety hazard on Road No. 36";
const initialBody = "A large pothole has developed on Road No. 36, Jubilee Hills, and has remained unresolved for approximately one week. Water is accumulating inside the damaged section, making the pothole difficult to identify, particularly for two-wheelers and pedestrians. The issue is creating a significant safety risk and is affecting residents and commuters using this road. There is currently no visible warning barricade near the damaged portion. Kindly inspect the location and arrange for urgent road repair and appropriate safety measures.";

export function ScanExperience() {
  const [step, setStep] = useState<Step>("camera");
  const [place, setPlace] = useState(address);
  const [editing, setEditing] = useState(false);
  const [selected, setSelected] = useState<number | null>(null);
  const [mode, setMode] = useState<"ai" | "write">("ai");
  const [q, setQ] = useState(0);
  const [answers, setAnswers] = useState<Record<number, string[]>>({});
  const [generated, setGenerated] = useState(false);
  const [approved, setApproved] = useState(false);
  const [title, setTitle] = useState(initialTitle);
  const [body, setBody] = useState(initialBody);
  const [authTab, setAuthTab] = useState<"mobile" | "email">("mobile");
  const [otpSent, setOtpSent] = useState(false);
  const [otp, setOtp] = useState("");
  const [email, setEmail] = useState("demo@drishti.gov.in");
  const [password, setPassword] = useState("Demo@123");
  const [error, setError] = useState("");
  useEffect(() => {
    if (step !== "analysing" && step !== "submitting") return;
    const timer = setTimeout(() => setStep(step === "analysing" ? "analysis" : "success"), 2300);
    return () => clearTimeout(timer);
  }, [step]);
  function answer(value: string) {
    const multi = q === 2 || q === 3;
    setAnswers(a => ({...a, [q]: multi ? (a[q]?.includes(value) ? a[q].filter(x => x !== value) : [...(a[q] || []), value]) : [value]}));
  }
  function authenticate() {
    const okay = authTab === "mobile" ? otp === "123456" : email === "demo@drishti.gov.in" && password === "Demo@123";
    if (!okay) return setError(authTab === "mobile" ? "Enter the demo OTP 123456." : "Use the demo credentials shown below.");
    setStep("submitting");
  }
  if (step === "camera") return <Camera load={() => setStep("analysing")} />;
  if (step === "analysing") return <Loading title="Understanding what you scanned…" lines={["Detecting the road issue", "Checking GPS and location", "Finding the probable authority", "Looking for nearby complaints"]}/>;
  if (step === "submitting") return <Loading title="Submitting your grievance…" lines={["Validating grievance", "Checking duplicate reports", "Routing to department", "Creating grievance reference"]}/>;
  const index: Record<Step, number> = {camera:0, analysing:1, analysis:1, nearby:2, builder:3, review:4, auth:5, submitting:5, success:5, track:5};
  return <main id="main" className="min-h-screen bg-surface text-navy">
    <header className="sticky top-0 z-30 border-b border-assist-line bg-white/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-4xl items-center justify-between px-4"><button onClick={() => history.back()} className="min-h-11 text-sm font-bold">← Back</button><Link href="/" className="text-xl font-black tracking-[-.05em]">Drishtee</Link><button aria-label="Read aloud" className="grid h-11 w-11 place-items-center rounded-full border border-assist-line">◖))</button></div></header>
    {step !== "success" && step !== "track" && <Progress active={index[step]}/>}<div className="mx-auto max-w-3xl px-4 py-9 md:py-12">
      {step === "analysis" && <Analysis place={place} setPlace={setPlace} editing={editing} setEditing={setEditing} next={() => setStep("nearby")}/>} 
      {step === "nearby" && <Nearby selected={selected} setSelected={setSelected} next={() => setStep("builder")}/>} 
      {step === "builder" && <Builder mode={mode} setMode={setMode} q={q} setQ={setQ} answers={answers} answer={answer} generated={generated} generate={() => setGenerated(true)} approved={approved} setApproved={setApproved} title={title} setTitle={setTitle} body={body} setBody={setBody} review={() => setStep("review")}/>} 
      {step === "review" && <Review title={title} body={body} place={place} linked={selected} edit={() => setStep("builder")} submit={() => setStep("auth")}/>} 
      {step === "auth" && <Auth tab={authTab} setTab={setAuthTab} otpSent={otpSent} setOtpSent={setOtpSent} otp={otp} setOtp={setOtp} email={email} setEmail={setEmail} password={password} setPassword={setPassword} error={error} authenticate={authenticate}/>} 
      {step === "success" && <Success track={() => setStep("track")}/>} {step === "track" && <Track/>}
    </div>
  </main>;
}

function Camera({load}:{load:()=>void}) { return <main className="relative min-h-[100svh] overflow-hidden bg-[#071528] text-white"><Image src="/pothole-scan.png" alt="Water-filled pothole on a damaged road" fill priority className="object-cover opacity-75"/><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(4,14,28,.75),transparent_35%,transparent_65%,rgba(4,14,28,.9))]"/><div className="relative z-10 mx-auto flex min-h-[100svh] max-w-2xl flex-col p-5"><div className="flex justify-between"><Link href="/" className="grid h-12 w-12 place-items-center rounded-full bg-black/40 text-2xl">×</Link><span className="rounded-full bg-black/40 px-4 py-3 text-sm font-bold">Scan & Report</span><button className="grid h-12 w-12 place-items-center rounded-full bg-black/40 text-xl">ϟ</button></div><div className="scan-frame relative my-auto aspect-[4/3] rounded-[28px] border border-white/60"><span className="anim-camera-line absolute inset-x-6 top-1/2 h-0.5 bg-[#60E08B] shadow-[0_0_18px_#60E08B]"/></div><div className="text-center"><h1 className="text-2xl font-semibold">Point at the public-service issue</h1><p className="mt-2 text-sm text-white/75">Keep the issue inside the frame.</p><div className="mt-5 flex items-end justify-center gap-8"><button className="text-xs"><span className="mb-1 grid h-12 w-12 place-items-center rounded-xl bg-white/15 text-xl">▧</span>Gallery</button><button onClick={load} className="grid h-20 w-20 place-items-center rounded-full border-4 border-white bg-white/20"><span className="h-14 w-14 rounded-full bg-white"/></button><button onClick={load} className="text-xs"><span className="mb-1 grid h-12 w-12 place-items-center rounded-xl bg-assist-green text-xl">▶</span>Load Sample</button></div></div></div></main> }

function Loading({title,lines}:{title:string;lines:string[]}) { const [done,setDone]=useState(0); useEffect(()=>{const t=setInterval(()=>setDone(d=>Math.min(d+1,lines.length)),450);return()=>clearInterval(t)},[lines.length]); return <main className="grid min-h-screen place-items-center bg-surface px-4 text-navy"><div className="w-full max-w-md text-center"><div className="relative mx-auto h-40 w-40 overflow-hidden rounded-3xl"><Image src="/pothole-scan.png" alt="Scanned pothole" fill className="object-cover"/><span className="anim-camera-line absolute inset-x-0 top-1/2 h-0.5 bg-[#60E08B]"/></div><h1 className="mt-7 text-3xl font-semibold">{title}</h1><div className="mt-6 grid gap-3 text-left">{lines.map((x,i)=><p key={x} className={`rounded-xl border px-4 py-3 text-sm font-bold ${i<done?"border-[#CDEBD7] bg-mint text-[#176C39]":"border-assist-line bg-white text-[#718096]"}`}>{i<done?"✓":"○"}<span className="ml-2">{x}</span></p>)}</div></div></main> }

function Progress({active}:{active:number}) { return <div className="border-b border-assist-line bg-white"><div className="mx-auto flex max-w-3xl px-4 py-3">{["Scan","Understand","Check","Create","Review","Submit"].map((x,i)=><div key={x} className="flex flex-1 items-center last:flex-none"><span className={`grid h-7 w-7 place-items-center rounded-full text-[11px] font-black ${i<=active?"bg-assist-blue text-white":"bg-surface-2 text-[#718096]"}`}>{i<active?"✓":i+1}</span><span className="ml-2 hidden text-xs font-bold sm:block">{x}</span>{i<5&&<span className={`mx-2 h-px flex-1 ${i<active?"bg-assist-blue":"bg-assist-line"}`}/>}</div>)}</div></div> }
function Detail({label,value}:{label:string;value:string}) { return <div><p className="text-xs font-black uppercase tracking-wide text-[#78869A]">{label}</p><p className="mt-1 text-sm font-semibold leading-6">{value}</p></div> }

function Analysis(p:{place:string;setPlace:(x:string)=>void;editing:boolean;setEditing:(x:boolean)=>void;next:()=>void}) { return <><p className="eyebrow">Scan analysis</p><h1 className="screen-title">We found a road-safety issue.</h1><p className="screen-copy">Review the details before continuing. You can change anything.</p><div className="mt-7 overflow-hidden rounded-3xl border border-assist-line bg-white shadow-[var(--elev-2)]"><div className="relative aspect-[16/9]"><Image src="/pothole-scan.png" alt="Scanned water-filled pothole" fill className="object-cover"/><span className="absolute left-4 top-4 rounded-full bg-[#A72B24] px-3 py-1.5 text-xs font-black text-white">High severity</span></div><div className="p-5 md:p-7"><span className="rounded-full bg-mint px-3 py-1.5 text-xs font-black text-[#176C39]">AI detected · 94% confidence</span><h2 className="mt-4 text-2xl font-semibold">Large pothole with accumulated water creating a road-safety hazard.</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><Detail label="Category" value="Roads → Pothole / Damaged Surface"/><Detail label="Suggested department" value="Greater Hyderabad Municipal Corporation – Roads Maintenance"/><Detail label="Location" value={p.place}/><Detail label="Coordinates" value="17.4318° N, 78.4073° E"/></div><p className="mt-5 rounded-xl bg-sky p-4 text-sm leading-6 text-[#415772]">Drishtee uses the image and your location to suggest the most relevant department. You can review and change this.</p></div></div><section className="mt-6 rounded-3xl border border-assist-line bg-white p-5 md:p-7"><div className="flex justify-between"><div><p className="eyebrow">Confirm location</p><h2 className="mt-1 text-2xl font-semibold">Is this the right place?</h2></div><button onClick={()=>p.setEditing(!p.editing)} className="h-11 rounded-full border border-assist-line px-4 text-sm font-bold">{p.editing?"Done":"Edit"}</button></div><div className="map-box relative mt-5 h-36 overflow-hidden rounded-2xl"><span className="absolute left-1/2 top-1/2 grid h-11 w-11 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-assist-blue text-white shadow-lg">●</span></div>{p.editing?<input value={p.place} onChange={e=>p.setPlace(e.target.value)} className="mt-4 min-h-12 w-full rounded-xl border border-assist-line px-4"/>:<div className="mt-4"><Detail label="Address" value={p.place}/><p className="mt-3 text-sm font-semibold">Landmark: Near Jubilee Hills Check Post</p></div>}<button onClick={()=>p.setPlace(address)} className="mt-4 min-h-12 w-full rounded-xl border border-assist-line font-bold text-assist-blue">⌖ Use my current location</button></section><button onClick={p.next} className="primary-cta">Confirm location & check nearby issues →</button></> }

function Nearby(p:{selected:number|null;setSelected:(x:number)=>void;next:()=>void}) { return <><span className="rounded-full bg-mint px-3 py-1.5 text-xs font-black text-[#176C39]">Duplicate check complete</span><h1 className="screen-title">We found similar open issues nearby.</h1><p className="screen-copy">Supporting the same issue helps the department see how many people are affected.</p><div className="mt-7 grid gap-4">{issues.map((x,i)=><article key={x[3]} className={`rounded-2xl border bg-white p-5 ${p.selected===i?"border-assist-blue shadow-[var(--elev-2)]":"border-assist-line"}`}><div className="flex justify-between gap-3"><div><span className="rounded-full bg-sky px-2.5 py-1 text-xs font-black text-assist-blue">{x[1]}</span><h2 className="mt-3 text-xl font-semibold">{x[0]}</h2></div><strong className="text-sm text-assist-green">{x[2]}</strong></div><p className="mt-3 text-sm text-[#617087]">Reported 2 days ago · {x[3]} · {x[4]} supporters</p><div className="mt-4 flex gap-2"><button className="pill">View details</button><button onClick={()=>p.setSelected(i)} className={`pill ${p.selected===i?"bg-assist-blue text-white":"bg-sky text-assist-blue"}`}>{p.selected===i?"✓ Selected":"This is the same issue"}</button></div></article>)}</div>{p.selected!==null&&<div className="mt-5 rounded-2xl bg-mint p-5"><h3 className="font-black">Add your support and evidence</h3><textarea className="mt-3 min-h-24 w-full rounded-xl border border-[#B6DCC2] bg-white p-3" placeholder="Add more context (optional)"/><button onClick={p.next} className="mt-3 min-h-12 w-full rounded-xl bg-assist-green font-black text-white">Continue with this issue →</button></div>}<div className="my-6 flex items-center gap-3 text-xs font-black text-[#78869A]"><span className="h-px flex-1 bg-assist-line"/>OR<span className="h-px flex-1 bg-assist-line"/></div><button onClick={()=>{p.setSelected(-1);p.next()}} className="min-h-14 w-full rounded-xl border-2 border-navy bg-white font-black">Report a different issue</button></> }

function Builder(p:{mode:"ai"|"write";setMode:(x:"ai"|"write")=>void;q:number;setQ:(x:number)=>void;answers:Record<number,string[]>;answer:(x:string)=>void;generated:boolean;generate:()=>void;approved:boolean;setApproved:(x:boolean)=>void;title:string;setTitle:(x:string)=>void;body:string;setBody:(x:string)=>void;review:()=>void}) { const [question,raw]=questions[p.q]; return <><p className="eyebrow">Create complaint</p><h1 className="screen-title">How would you like to prepare it?</h1><div className="mt-6 grid grid-cols-2 gap-3"><button onClick={()=>p.setMode("ai")} className={`mode-card ${p.mode==="ai"?"active":""}`}><strong>✦ AI Assist</strong><span>Answer simple questions</span></button><button onClick={()=>p.setMode("write")} className={`mode-card ${p.mode==="write"?"active":""}`}><strong>✎ Write Myself</strong><span>Use a familiar form</span></button></div>{p.mode==="write"?<DraftForm {...p}/>:p.generated?<Generated {...p}/>:<div className="mt-7"><div className="flex justify-between text-xs font-black"><span>Question {p.q+1} of 6</span><span>{Math.round((p.q+1)/6*100)}%</span></div><div className="mt-2 h-2 rounded-full bg-surface-2"><span className="block h-full rounded-full bg-assist-blue" style={{width:`${(p.q+1)/6*100}%`}}/></div><div className="mt-5 rounded-2xl border border-assist-line bg-white p-5"><div className="flex justify-between"><h2 className="text-2xl font-semibold">{question}</h2><button className="h-11 w-11 shrink-0 rounded-full border border-assist-line">◖))</button></div><div className="mt-5 flex flex-wrap gap-2">{raw.split("|").map(x=><button key={x} onClick={()=>p.answer(x)} className={`choice ${p.answers[p.q]?.includes(x)?"selected":""}`}>{x}</button>)}</div><div className="mt-6 flex gap-3"><button disabled={!p.q} onClick={()=>p.setQ(p.q-1)} className="pill disabled:opacity-30">Back</button><button disabled={!p.answers[p.q]?.length} onClick={()=>p.q===5?p.generate():p.setQ(p.q+1)} className="min-h-12 flex-1 rounded-xl bg-navy font-black text-white disabled:opacity-40">{p.q===5?"Prepare my grievance ✦":"Continue →"}</button></div></div></div>}</> }
function DraftForm(p:{title:string;setTitle:(x:string)=>void;body:string;setBody:(x:string)=>void;review:()=>void}) { return <div className="form-card"><label>Complaint title<input value={p.title} onChange={e=>p.setTitle(e.target.value)}/></label><label>Description<textarea value={p.body} onChange={e=>p.setBody(e.target.value)}/></label><Detail label="Department" value="Greater Hyderabad Municipal Corporation"/><Detail label="Category" value="Roads → Pothole / Damaged Road"/><button onClick={p.review} className="min-h-13 rounded-xl bg-navy font-black text-white">Review complaint →</button></div> }
function Generated(p:{title:string;setTitle:(x:string)=>void;body:string;setBody:(x:string)=>void;approved:boolean;setApproved:(x:boolean)=>void;review:()=>void}) { return <div className="form-card shadow-[var(--elev-2)]"><span className="w-fit rounded-full bg-sky px-3 py-1.5 text-xs font-black text-assist-blue">✦ AI-drafted — please review</span><input value={p.title} onChange={e=>p.setTitle(e.target.value)} className="text-xl font-black"/><textarea value={p.body} onChange={e=>p.setBody(e.target.value)} className="min-h-56 leading-7"/><div className="flex flex-wrap gap-2">{["Regenerate","Make shorter","Add more detail","Simple tone"].map(x=><button className="pill" key={x}>{x}</button>)}</div><label className="flex-row! items-center gap-3 rounded-xl bg-mint p-4"><input type="checkbox" className="h-5! w-5!" checked={p.approved} onChange={e=>p.setApproved(e.target.checked)}/>I have reviewed and approve this complaint</label><button disabled={!p.approved} onClick={p.review} className="min-h-13 rounded-xl bg-navy font-black text-white disabled:opacity-40">Continue to review →</button></div> }

function Review(p:{title:string;body:string;place:string;linked:number|null;edit:()=>void;submit:()=>void}) { return <><p className="eyebrow">Review before submitting</p><h1 className="screen-title">Your grievance is ready.</h1><p className="screen-copy">Check every detail. You’ll sign in only when you submit.</p><div className="mt-7 grid gap-4">{[["Complaint",p.title,p.body],["Issue","Roads → Pothole / Damaged Road","High severity"],["Department","Greater Hyderabad Municipal Corporation","Road Maintenance / Engineering Wing"],["Location",p.place,"Near Jubilee Hills Check Post"]].map(x=><section key={x[0]} className="review-card"><div className="flex justify-between"><p className="eyebrow">{x[0]}</p><button onClick={p.edit} className="text-sm font-bold text-assist-blue">Edit</button></div><h2 className="mt-3 text-lg font-black">{x[1]}</h2><p className="mt-2 text-sm leading-6 text-[#596A80]">{x[2]}</p></section>)}<section className="review-card"><p className="eyebrow">Evidence</p><div className="relative mt-3 h-36 overflow-hidden rounded-xl"><Image src="/pothole-scan.png" alt="Pothole evidence" fill className="object-cover"/></div></section>{p.linked!==null&&p.linked>=0&&<section className="rounded-2xl bg-mint p-5"><p className="eyebrow">Related issue</p><h2 className="mt-2 font-black">{issues[p.linked][0]}</h2></section>}</div><button onClick={p.submit} className="primary-cta bg-assist-green!">Submit Grievance →</button><p className="mt-3 text-center text-xs text-[#718096]">Your draft stays saved while you sign in.</p></> }

function Auth(p:{tab:"mobile"|"email";setTab:(x:"mobile"|"email")=>void;otpSent:boolean;setOtpSent:(x:boolean)=>void;otp:string;setOtp:(x:string)=>void;email:string;setEmail:(x:string)=>void;password:string;setPassword:(x:string)=>void;error:string;authenticate:()=>void}) { return <div className="mx-auto max-w-md"><div className="text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-mint text-2xl">✓</span><h1 className="mt-4 text-3xl font-semibold">Sign in to submit your grievance</h1><p className="mt-3 text-sm text-[#617087]">Your complaint is ready. Sign in to submit it and track updates.</p></div><div className="mt-7 rounded-3xl border border-assist-line bg-white p-5 shadow-[var(--elev-2)]"><div className="grid grid-cols-2 rounded-xl bg-surface-2 p-1">{(["mobile","email"] as const).map(x=><button key={x} onClick={()=>p.setTab(x)} className={`min-h-11 rounded-lg font-black capitalize ${p.tab===x?"bg-white shadow":""}`}>{x}</button>)}</div>{p.tab==="mobile"?<div className="mt-5">{!p.otpSent?<><label className="form-label">Mobile number<input defaultValue="9876543210"/></label><button onClick={()=>p.setOtpSent(true)} className="auth-button">Send OTP</button></>:<><p className="text-sm text-[#617087]">Enter the 6-digit OTP sent to your mobile.</p><input autoFocus value={p.otp} onChange={e=>p.setOtp(e.target.value.replace(/\D/g,""))} maxLength={6} className="otp" placeholder="••••••"/><p className="mt-2 text-xs">Demo OTP: <strong>123456</strong></p><button onClick={p.authenticate} className="auth-button">Verify & submit</button></>}</div>:<div className="mt-5 grid gap-4"><label className="form-label">Email address<input value={p.email} onChange={e=>p.setEmail(e.target.value)}/></label><label className="form-label">Password<input type="password" value={p.password} onChange={e=>p.setPassword(e.target.value)}/></label><button onClick={p.authenticate} className="auth-button mt-0!">Sign in & submit</button><button className="text-sm font-bold text-assist-blue">Create account</button><p className="text-xs">Demo: demo@drishti.gov.in / Demo@123</p></div>}{p.error&&<p className="mt-4 rounded-xl bg-[#FBEAE9] p-3 text-sm font-bold text-[#A72B24]">{p.error}</p>}</div></div> }

function Success({track}:{track:()=>void}) { return <div className="mx-auto max-w-xl text-center"><span className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-assist-green text-4xl text-white">✓</span><p className="mt-6 eyebrow">Submission complete</p><h1 className="screen-title">Grievance submitted successfully</h1><div className="mt-7 rounded-3xl border border-assist-line bg-white p-6 text-left shadow-[var(--elev-2)]"><Detail label="Reference ID" value="GRV-HYD-2026-19284"/><div className="mt-5 grid gap-4 sm:grid-cols-2"><Detail label="Department" value="Greater Hyderabad Municipal Corporation"/><Detail label="Status" value="Submitted"/><Detail label="Expected acknowledgement" value="Within 24 hours"/><Detail label="Nearby concerns" value="12 reports within 500 m"/></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><button onClick={track} className="auth-button mt-0!">Track grievance</button><button className="secondary">Download acknowledgement</button><button className="secondary">Share reference</button><Link href="/" className="secondary">Back to home</Link></div></div> }
function Track() { const stages=["Submitted","Acknowledged","Assigned to Department","Officer Review","Action in Progress","Resolved"]; return <><p className="eyebrow">Track grievance</p><h1 className="screen-title">Assigned to Department</h1><p className="screen-copy">GRV-HYD-2026-19284 · Last updated today</p><div className="mt-7 review-card">{stages.map((x,i)=><div key={x} className="flex min-h-16 gap-4"><div className="flex flex-col items-center"><span className={`grid h-8 w-8 place-items-center rounded-full text-xs font-black ${i<=2?"bg-assist-green text-white":"border-2 border-assist-line"}`}>{i<2?"✓":i+1}</span>{i<5&&<span className={`w-0.5 flex-1 ${i<2?"bg-assist-green":"bg-assist-line"}`}/>}</div><div><strong>{x}</strong>{i===2&&<p className="mt-1 text-sm text-[#617087]">Assigned to Assistant Engineer – Roads Division 9.</p>}</div></div>)}</div><Link href="/" className="primary-cta flex items-center justify-center">Back to home</Link></> }
